openapi: 3.0.0

info:
  version: 1.0.0
  title: Secret santa.
  description: Secret santa.

servers:
  - description: Local
    url: https://localhost/api/v1/santa

components:
  schemas:
    BaseObject:
      description: Common fields from general response.
      type: object
      properties:
        status:
          type: integer
          format: int32
          description: Status.
    
    TeammateObject:
      allOf:
        - $ref: '#/components/schemas/BaseObject'
        - type: object
          properties:
            response:
              type: string
              description: Teammate's name.
    
    SantaMappingObject:
      type: object
      properties:
        santa:
          type: string
          description: Santa's name.
        receiver:
          type: string
          description: Name of person who gets the gift from Santa.
    
    SantasObject:
      allOf:
        - $ref: '#/components/schemas/BaseObject'
        - type: object
          properties:
            response:
              type: array
              items:
                $ref: '#/components/schemas/SantaMappingObject'
      
  
  parameters:
    TeammateParam:
      in: query
      name: name
      schema:
        type: string
      required: true
      description: Teammate name.
    
    YearParam:
      in: query
      name: year
      schema:
        type: integer
        format: int64
      required: false
      description: Year - default current year.
  
  responses:
    TemateResp:
      description: OK
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/TeammateObject'
    
    SantasResp:
      description: OK
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SantasObject'

paths:
  /teammate:
    post:
      summary: Register a new teammate.
      description: Service creates a new entity in the game.
      parameters:
        - $ref: '#/components/parameters/TeammateParam'
      responses:
        201:
          $ref: '#/components/responses/TemateResp'
  
  /santas:
    get:
      summary: Return santas with receivers.
      description: Service returns santas with receivers.
      responses:
        200:
          $ref: '#/components/responses/SantasResp'
  
  /santas/reset_year:
    put:
      summary: Reset year. To be used after Secret Santa party.
      description: Service cleans current santas and send all santas (current_year - 1). Note taht only two years back are being kept.
      responses:
        200:
          $ref: '#/components/responses/SantasResp'
      
