/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (5.3.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.secret.santa.api;

import com.secret.santa.model.TeammateObject;
import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2021-12-17T17:58:40.017983Z[Europe/Dublin]")
@Validated
@Api(value = "teammate", description = "the teammate API")
public interface TeammateApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * POST /teammate : Register a new teammate.
     * Service creates a new entity in the game.
     *
     * @param name Teammate name. (required)
     * @return OK (status code 201)
     */
    @ApiOperation(value = "Register a new teammate.", nickname = "teammatePost", notes = "Service creates a new entity in the game.", response = TeammateObject.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "OK", response = TeammateObject.class) })
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/teammate",
        produces = { "application/json" }
    )
    default ResponseEntity<TeammateObject> teammatePost(@NotNull @ApiParam(value = "Teammate name.", required = true) @Valid @RequestParam(value = "name", required = true) String name) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "null";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
